---

- hosts: 127.0.0.1
  user: that1guy15
  sudo: True

  vars:
    device_name: "{{device_name}}"
    device_ip: "{{device_ip}}"
    device_role: "{{device_role}}"
    device_network: "{{device_network}}"
    username: "{{username}}"
    password: "{{password}}"


  tasks:
    - name: create device folder
      file:
        dest: "/srv/netmgmt/inventory/{{device_name}}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Check for hosts file
      stat:
        path: "/srv/netmgmt/inventory/hosts"
      register: stat_result

    - name: create hosts file if missing
      file:
        path: "/srv/netmgmt/inventory/hosts"
        owner: root
        group: root
        mode: 0755
        state: touch
      when: stat_result.stat.exists == False

    - name: create device detail file
      template:
        src: templates/device_detail.j2
        dest: "/srv/netmgmt/inventory/{{device_name}}/{{device_name}}.yaml"
        owner: root
        group: root
        mode: 644

    - name: Update ansible inventory file
      blockinfile:
        path: "/srv/netmgmt/inventory/hosts"
        insertafter: "{{device_network}}-{{device_role}}"
        backup: yes
        content: |
          {{device_name}} ansible_host={{device_ip}} role={{device_role}} network={{device_network}}

